id = "webidl"
name = "WebIDL"
version = "0.0.1"
schema_version = 1
authors = ["Samantha Nguyen <contact@samanthanguyen.me>"]
description = "WebIDL syntax highlighting support for Zed."
repository = "https://github.com/neoncitylights/zed-webidl"

[grammars.webidl]
repository = "https://github.com/neoncitylights/tree-sitter-webidl"
rev = "5dd356f957d35735dccc5171f598080482aceeb7"
